language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO_VERSION=1.4.13
  - DJANGO_VERSION=1.5.8
  - DJANGO_VERSION=1.6.5

matrix:
  exclude:
    - python: 3.2
      env: DJANGO_VERSION=Django==1.4.13
    - python: 3.3
      env: DJANGO_VERSION=Django==1.4.13

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - coverage run --source=registration setup.py test

after_success:
  - coveralls --verbose
