language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=Django==1.4.20
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.11
  - DJANGO=Django==1.7.7
  - DJANGO=Django==1.8

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=Django==1.4.20
    - python: 3.3
      env: DJANGO=Django==1.4.20
    - python: 2.6
      env: DJANGO=Django==1.7.7
    - python: 2.6
      env: DJANGO=Django==1.8

install:
  - pip install -q $DJANGO
  - pip install coveralls
  - python setup.py -q install

before_script:
  - rm -rf build

script:
  - coverage run --source=registration setup.py test

after_success:
  - coveralls --verbose
